Chats/urls.py
from django.contrib import admin
from django.urls import path, include
from . import  views




urlpatterns = [
    path('chat/', views.MessageView.as_view(), name='chat'),
    path('chat/<int:id>/', views.Inbox, name = 'inbox' ),
    
]

FESSEF/urls.py
from django.contrib import admin
from django.urls import path, include
from Postfeeds import views
from django.conf import settings 
from django.conf.urls.static import static

admin.site.site_header = "Fessef"
admin.site.site_title = "Fessef Admin Panel"
admin.site.index_title = "Bienvenue dans Fessef Admin Panel"




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('utilisateurs.urls')),
    # path('tinymce/', include('tinymce.urls')),
    # path('like/', views.like_post, name='like_post'),
    # path('Chats/', include('Chats.urls'), name='Chats'),
    # path('ckeditor/', include('ckeditor_uploader.urls')),
    # path('summernote/', include('django_summernote.urls')),
    # path('xamxam/', include('xamxam.urls'), name='xamxam'),
    
    # # Link Evenements App
    # path('event/', include('event.urls'), name='event'),
    # path('evenadmin/', include('evenadmin.urls'), name='evenadmin'),
    
    # # path('oauth/', include('social_django.urls', namespace='social')),
    # path('reporting/', include('reporting.urls'), name='reporting'),
    # path('postfeeds/', include('Postfeeds.urls'), name='postfeeds'),
    # path('Competence/', include('Competence.urls'), name='Competence'),
    # path('annonceEtpse/', include('AnnonceEtpse.urls'), name='annonceEtpse'),
    # path('notifications/', include('notifications.urls'), name='notifications'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

xamxam/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views




urlpatterns = [
    path('xamxam/', views.XamxamView.as_view(), name='xamxam'),
    path("addxamxam/", views.AddXamxam.as_view(), name='addxamxam'),
    path('xamxam/tagg/<slug:slug>/', views.Taggedd, name="taggedXam"),
    path("sup/<int:id>", views.DelXamxam, name='delxamxam'),
    path('xamxam/<int:id>/', views.XamxaDetailView, name = 'Xdetails' ),
    path('xamxam/edit/<int:pk>/', views.UpdateXamxamView.as_view(), name = 'updatexamxam'),
    # path('xamxam/category/<slug:slug>/', views.category, name="category"),
    # path("update/<int:id>", views.UpdateXamxam, name='updatexamxam'),
    
]

xamxam/models.py
from django.db import models
from django.urls import reverse
from utilisateurs.models import User
from django.template.defaultfilters import slugify
from taggit.managers import TaggableManager



# class Category(models.Model):
#     title     = models.CharField(max_length=255, default='Autre')
#     slug      = models.SlugField()



#     class Meta:
#         verbose_name_plural = "Categories"
    
#     # function for add slug
#     def save(self, *args, **kwargs):
#         self.slug = slugify(self.title)
#         super(Category, self).save(*args, **kwargs)

#     def __str__(self):
#         return self.title


class Xamxam(models.Model):
    author    = models.ForeignKey(User, on_delete=models.CASCADE)
    # category  = models.ForeignKey(Category, related_name="posts", on_delete=models.CASCADE)
    thumbnail = models.ImageField(upload_to = "feseul_image", null=True, blank = True)
    views     = models.IntegerField(default=0, null=True, blank = True)
    slug      = models.SlugField()
    timestamp = models.DateTimeField(auto_now_add=True)
    archive   = models.BooleanField(default=False)
    title     = models.CharField(max_length=255)
    tags      = TaggableManager() 
    contenu   = models.TextField()


    # function for add slug
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Xamxam, self).save(*args, **kwargs)

    def __str__(self):
        return f"{self.author } -||- {self.timestamp.date()}"

    def get_absolute_url(self):
        # return reverse('annonce-datail', args=(str(self.id))) 
        return reverse('xamxam')

xamxam/forms.py
from django_summernote.fields import SummernoteTextFormField, SummernoteTextField
from django_summernote.widgets import SummernoteWidget, SummernoteInplaceWidget

from .models import Xamxam
from django import forms





class XamxamForm(forms.ModelForm):
    class Meta:

        model = Xamxam 
        fields = ('author', 'thumbnail', 'title', 'tags',  'contenu')

        widgets = {
            'author'  : forms.TextInput(attrs={'class' : 'form-control', 'value' : '', 'id' : 'username', 'type' : 'hidden' }),
            'title'   : forms.TextInput(attrs={'class' : 'form-control', 'label':'Titre :', 'placeholder': 'Entrez votre titre...'}),
            'tags'    : forms.TextInput(attrs={'class' : 'form-control',   'type' : 'text', 'data-role' : 'tagsinput' }),
            # 'contenu' : forms.Textarea(attrs={'class' : 'form-control', 'placeholder': 'Entrez Le contenu...'}),
            'contenu' : SummernoteWidget(),
        }


class UpdateForm(forms.ModelForm):
    class Meta:
        model = Xamxam 
        fields = ('thumbnail', 'title', 'tags', 'contenu')

        widgets = {
            'title' : forms.TextInput(attrs={'class' : 'form-control', 'placeholder': 'Entrez votre titre...'}),
            # 'contenu' : forms.Textarea(attrs={'class' : 'form-control', 'placeholder': 'Entrez Le contenu...'}),
            'contenu' : SummernoteWidget(),   
        }

        

xamxam/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import( ListView, 
                CreateView, UpdateView, DeleteView)
from django.urls import reverse_lazy, reverse
from .forms import XamxamForm, UpdateForm
from taggit.models import Tag
from .models import Xamxam 




def Taggedd(request, slug):
    tag                 = get_object_or_404(Tag, slug=slug)
    posts               = Xamxam.objects.filter(tags = tag)
    common_Tags         = Xamxam.tags.most_common()[:10]
    context             = {
        'tag'         : tag,
        'posts'       : posts,
        'common_Tags' : common_Tags
    }
    return render(request, 'xamxam/xamaxam.html', context)


# fonction pour Ajouter un post xamxam
class AddXamxam(CreateView):
    model           =  Xamxam
    form_class      =  XamxamForm
    template_name   = 'xamxam/addxamxam.html'




# fonction pour modifier son post xamxam
class UpdateXamxamView(UpdateView):
    model           =  Xamxam
    form_class      =  UpdateForm
    template_name   = 'xamxam/updatexamxam.html' 
    # fields = ['title', 'thumbnail', 'contenu']






# Fonction pour avoir tous les posts xamxam
class XamxamView(ListView):
    
    model = Xamxam
    template_name = 'xamxam/xamaxam.html'
    ordering = ['-timestamp']
    context_object_name = 'posts'

    

# Pour avoir les details de l'article
def XamxaDetailView(request, id):
    post = Xamxam.objects.get(id=id)
    post.views = post.views + 1
    post.save()

    context = {
        'post' : post,
    }

    return render(request, 'xamxam/xamDetails.html', context)


#categori
# def category(request, slug):
#     category = Category.objects.get(slug=slug)
#     context = {
#         'category' : category
#     }
#     return render(request, 'xamxam/category.html', context)



# suprimer un post xamxam
def DelXamxam(request, id):
    post_ = get_object_or_404(Xamxam, id=id)
    post_.delete()
    return redirect('xamxam')

templates/xamxam/addxamxam.html
{% extends 'base/base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'CSS/addxamaxam.css' %}">

    <style>
        #id_thumbnail
        {
          margin-top: 5px;
          font-size : 16px;
          background: white;
          border-radius: 50px;
          width: 100%;
          outline: none;
          box-shadow: 10px 14px 23px -4px rgba(0,0,0,0.1);
          -webkit-box-shadow: 10px 14px 23px -4px rgba(0,0,0,0.29);
          -moz-box-shadow: 10px 14px 23px -4px rgba(0,0,0,0.29);
        }
      
        ::-webkit-file-upload-button
        {
          color: #fff;
          background:#3563A9;
          padding: 10px;
          border: none;
          border-radius: 50px;
          box-shadow: 1px 0 1px #052754;
          outline: none;
        }
      
        ::-webkit-file-upload-button:hover
        {
          background: #052754;
          box-shadow: 1px 0 1px #3563A9;
        }

        label[for="id_thumbnail"]
        {
          display: none;
        }
        .helptext
        {
            font-size: 15px;
            font-weight: 400;
            margin-top: -10px;
        }

        #btn-bleu
        {
          background-color: #3563A9;
          color: #fff;
          width: 100px;
          padding: 8px;
          border: none;
          border-radius: 20px;
          font-size: 20px;
        }
      
        #btn-bleu:hover
        {
          background-color: #fff;
          color: #3563A9;
          border: 1px solid #3563A9;
          transition: all 0.5s ease-out;
        }
    </style>

{% endblock css %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-3"></div>

        <!-- Debut du section formulaire -->
        <div class="col-md-6">

            <h1 class="h2">Créer un document<h2>
            <form method="POST" action="{% url 'addxamxam' %}" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="mb-4" id="btn-bleu">Partagez</button>

            </form>

            
        </div>
        <!-- Fin du section formulaire -->

        <div class="col-md-3"></div>
    </div>
</div>



<script>
    var name = "{{user.id}}";
    document.getElementById("username").value = name;

</script>

{% endblock content %}

{% block script %}
    <script>
        $(document).ready(function(){
            $('[for="id_title"]').text("Titre");
        });
       
    </script>
{% endblock script %}

templates/xamxam/category.html
{% extends 'base/base.html' %}
{% load static %}
{% block css %}
    {% if user.is_association%}
        <link href="{% static 'CSS/Associ.css' %}" rel="stylesheet" type="text/css">
    {% else %}
        <link rel="stylesheet" href="{% static 'CSS/etu_menu.css' %}">
    {% endif %}
    <link rel="stylesheet" href="{% static 'CSS/xamaxam.css' %}">
    <link rel="stylesheet" href="{% static 'CSS/cardImg.css' %}">
{% endblock css %}

{% block content %}

<!-- debut des menu -->
{% if user.is_student %}
    {% include 'partials/_etu_menu.html' %}
{% elif user.is_company %}
    {% include 'partials/_etpse_menu.html' %}
{% elif user.is_association %}
    {% include 'partials/_Association_Menu.html' %}
{% endif %}
<!-- debut des menu -->

<div class="container-fluid mt-2">
    <a href=" {% url 'addxamxam' %} "  class="btn btn-lg btn-warning m-2 ">
        Xamleul
    </a>

    <h2 class="text-primary"> {{category.title}} </h2>
    <div class="row my-2">

        {% for post in category.posts.all %}
        <div class="col-md-4 mb-4 resize">
            
            <div class="card mb-2" id="{{post.id}}">
                <div class="card-body">
                    <h5 class="card-title text-center">
                        <a class="text-dark" href=" {% url 'Xdetails' post.id%} " style="text-decoration: none;">
                            <strong>{{ post.title }}</strong>
                        </a>
                    </h5>

                </div>
                {% if post.thumbnail %}
                    <img src="{{ post.thumbnail.url }}" class="card-img-top img-fluid card-infoImgg" alt=" {{post.author}} " 
                    id="img_card">
                {% endif %}

                <div class="card-body">
                    <p class="text-center text-muted">Depuis {{post.timestamp|timesince}}</p>
                    <p class="card-text">{{ post.contenu|slice:":50"|safe }}
                        <a class="text-dark" href=" {% url 'Xdetails' post.id%} " >...</a>
                    </p>
                </div>

                
                {% if request.user == post.author %}
                <ul class="list-group list-group-flush text-center">
                    <li class="list-group-item">
                        <a href="{% url 'updatexamxam' post.pk %}" class="float-left d-inline ml-2 text-warning">
                            Modifier
                        </a>

                        <a href="{% url 'delxamxam' post.id %}" class="float-right d-inline mr-2 text-danger delete" id="{{post.id}}">
                            Suprimer
                        </a>
                    </li>
                </ul>
                {% endif %}
                <div class="card-footer ">
                    <p class="float-left d-inline  ml-2"><b>{{ post.author }}</b></p>
                    <p class="float-right d-inline mr-2" ></p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
        



{% endblock content %}

{% block script %}
    <script src="{% static 'JS/postfeeds.js' %}  "></script>
{% endblock script %}

templates/xamxam/updatexamxam.html
{% extends 'base/base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'CSS/addxamaxam.css' %}">
{% endblock css %}


{% block content %}

<div class="container mt-2">
    <div class="row ">
        <div class="col-md-2"></div>

        <!-- Debut du section formulaire -->
        <div class="col-md-8 mt-4">
            
            <div class="card mb-2">
                <div class="card-body text-center">
                    <h1>Editer Votre Document<h2>
                </div>
              </div>

            
            <form method="POST"  enctype="multipart/form-data" class="mt-2">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary"> Editer </button>

            </form>

            
        </div>
        <!-- Fin du section formulaire -->

        <div class="col-md-2"></div>
    </div>
</div>



{% endblock content %}



{% block script %}
{% endblock script %}

templates/xamxam/xamDetails.html
{% extends 'base/base.html' %}
{% load static %} 
{% block css %}
    {% if user.is_association%}
        <link href="{% static 'CSS/Associ.css' %}" rel="stylesheet" type="text/css">
    {% else %}
        <link rel="stylesheet" href="{% static 'CSS/etu_menu.css' %}">
    {% endif %}
    <link rel="stylesheet" href="{% static 'CSS/cardImg.css' %}">
{% endblock css %}

{% block content %}

<!-- debut des menu -->
{% if user.is_student %}
    {% include 'partials/_etu_menu.html' %}
{% elif user.is_company %}
    {% include 'partials/_etpse_menu.html' %}
{% elif user.is_association %}
    {% include 'partials/_Association_Menu.html' %}
{% endif %}
<!-- debut des menu -->


<div class="container-fluid ">
    <div class="row my-2">
        <div class="col-md-2"></div>
    
        <div class="col-md-8 m-4">

            <div class="card " id="{{i.id}}">
            {% if post.thumbnail %}
                <img src="{{ post.thumbnail.url }}" class="card-img-top img-fluid card-infoImgg" alt="...">
            {% endif %}

            <div class="card-body">
                <h5 class="card-title text-center"><a class="text-dark" href="" >
                <strong>{{ post.title }}</strong>
                </a></h5>
                <p class="text-center text-muted">Depuis {{post.timestamp|timesince}}</p>
                <p class="card-text">{{ post.contenu|safe }}</p>
            </div>
            {% if request.user == post.author %}
            <ul class="list-group list-group-flush text-center">
                <li class="list-group-item">
                    <a href="{% url 'updatexamxam' post.pk %}" class="float-left d-inline ml-2 text-warning">
                        Modifier
                    </a>
                    <a href="{% url 'delxamxam' post.id %}" class="float-right d-inline mr-2 text-danger delete" id="{{i.id}}">
                        Suprimer
                    </a>
                </li>
            </ul>
            {% endif %}
            <div class="card-footer text-muted text-center">

                <p class="float-left d-inline  ml-2">
                    <b>
                    {{ post.author }}
                    </b>
                </p>
                <p class="text-center d-inline ml-2">
                    <a class="text-muted" href=" # ">
                        Vue ({{ post.views }})
                    </a>
                </p>
                <p class="float-right d-inline mr-2" >
                    <a class="text-primary" href="{% url 'category' post.category.slug %} ">
                        {{ post.category.title }}
                    </a> 
                </p>
            </div>

            </div>

        </div>

        <div class="col-md-2"></div>
</div>
</div>




{% endblock content %}

{% block script %}
    <script src="{% static 'JS/postfeeds.js' %}  "></script>
{% endblock script %}

templates/xamxam/xamaxam.html
{% extends 'base/base.html' %}
{% load static %}
{% block css %}
    {% if user.is_association%}
        <link href="{% static 'CSS/Associ.css' %}" rel="stylesheet" type="text/css">
    {% else %}
        <link rel="stylesheet" href="{% static 'CSS/etu_menu.css' %}">
    {% endif %}
    <link rel="stylesheet" href="{% static 'CSS/xamaxam.css' %}">
    <link rel="stylesheet" href="{% static 'CSS/cardImg.css' %}">
{% endblock css %}

{% block content %}

<!-- debut des menu -->
{% if user.is_student %}
    {% include 'partials/_etu_menu.html' %}
{% elif user.is_company %}
    {% include 'partials/_etpse_menu.html' %}
{% elif user.is_association %}
    {% include 'partials/_Association_Menu.html' %}
{% endif %}
<!-- debut des menu -->

<div class="container-fluid mt-2">
    <a href=" {% url 'addxamxam' %} "  class="btn btn-lg text-white m-2 " style="background-color: #3563A9;">
        Xamleul
    </a>

    <div class="col-md-9 mt-4">
      <!-- <div class="row "> -->
       <!-- <h5 class="text-center mt-4 ml-4"> Categories :</h5> -->
        <!-- les 4 tags les plus utilisé  -->
        <!-- <p class="m-4">
          {% for post in xamaAll.posts.all %}
            <a class="text-primary" href="{% url 'category' post.category.slug %} ">
                {{ post.category.title }}
            </a> 
          {% endfor  %}
        </p> -->
        <!-- fin du div des tags -->
      </div> 

    <div class="row my-2">

        {% for post in posts %}
        <div class="col-md-4 mb-4 resize">
            
            <div class="card mb-2" id="{{post.id}}" onclick="location.href='{% url 'Xdetails' post.id %}';"  style="cursor: pointer;">
                <div class="card-body">
                    <h5 class="card-title text-center">
                        <a class="text-dark" href=" {% url 'Xdetails' post.id%} " style="text-decoration: none;">
                            <strong>{{ post.title }}</strong>
                        </a>
                    </h5>

                </div>
                {% if post.thumbnail %}
                    <img src="{{ post.thumbnail.url }}" class="card-img-top img-fluid card-infoImgg" alt=" {{post.author}} " 
                    id="img_card">
                {% endif %}

                <div class="card-body">
                    <p class="text-center text-muted">Depuis {{post.timestamp|timesince}}</p>
                    <p class="card-text">{{ post.contenu|slice:":50"|safe }}
                        <a class="text-dark" href=" {% url 'Xdetails' post.id%} " >...</a>
                    </p>
                </div>

                <!-- div tags -->
                <ul class="list-group list-group-flush text-center">
                    <li class="list-group-item">
                        <div style="display: flex;">
                            {% for tag in post.tags.all %}
                                <a href="{% url 'taggedXam'  tag.slug %}" class="badge badge-danger ml-1">
                                    #{{ tag }}
                                </a>
                            {% endfor  %}
                        </div>
                    </li>
                </ul>
                <!-- fin div tag -->
                
                {% if request.user == post.author %}
                <ul class="list-group list-group-flush text-center">
                    <li class="list-group-item">
                        <a href="{% url 'updatexamxam' post.pk %}" class="float-left d-inline ml-2 text-warning">
                            Modifier
                        </a>

                        <a href="{% url 'delxamxam' post.id %}" class="float-right d-inline mr-2 text-danger delete" id="{{post.id}}">
                            Suprimer
                        </a>

                    </li>
                </ul>
                {% endif %}
                <div class="card-footer ">
                    <p class="float-left d-inline  ml-2"><b>{{ post.author }}</b></p>
                    <p class="float-right d-inline mr-2" >
                        <!-- <a class="text-primary" href="{% url 'category' post.category.slug %} ">
                            {{ post.category.title }}
                        </a> 
                    </p> -->
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
        



{% endblock content %}

{% block script %}
    <script src="{% static 'JS/postfeeds.js' %}  "></script>
{% endblock script %}